name: 0 Enterprise Markdown → HTML (± PDF) Converter (self-reflecting, no cache)

on:
  workflow_dispatch:
    inputs:
      sync_path:
        description: 'Path to directory containing the Markdown file (e.g., ndr/v6.0/psd01)'
        required: true
        type: string
        default: ''
      operation_mode:
        description: >-
          What to do.
          - format_and_convert: run prettier + markdown→HTML
          - format_only: only prettier
          - convert_only: only markdown→HTML (no formatting)
          - format_convert_pdf: format, convert to HTML, then HTML→PDF (requires modify_date)
        required: true
        type: choice
        default: format_convert_pdf
        options:
          - format_and_convert
          - format_only
          - convert_only
          - format_convert_pdf
      modify_date:
        description: 'Modification date for PDF footer / timestamps (yyyy-mm-dd). Required for PDF generation.'
        required: false
        type: string
        default: '2025-01-27'

env:
  PYTHONUNBUFFERED: '1'
  PIP_NO_CACHE_DIR: '0'

permissions:
  contents: write
  workflows: write

jobs:
  reflect-inputs:
    name: Reflect Inputs into Workflow YAML
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write
    outputs:
      reflected: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Run reflection script
        env:
          SYNC_PATH: ${{ github.event.inputs.sync_path }}
          OP_MODE: ${{ github.event.inputs.operation_mode }}
          MODIFY_DATE: ${{ github.event.inputs.modify_date }}
          WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          chmod +x ./scripts/reflect-inputs.sh
          ./scripts/reflect-inputs.sh

      - name: Inline reflect inputs (fallback)
        if: failure()
        env:
          WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          # Ensure yq is installed
          if ! command -v yq >/dev/null 2>&1; then
            echo "Installing yq..."
            curl -fsSL -o /tmp/yq_linux_amd64 https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64
            sudo install -m 0755 /tmp/yq_linux_amd64 /usr/local/bin/yq
          fi
          yq --version

          WF=".github/workflows/enterprise-markdown-convert.yml"
          if [[ ! -f "$WF" ]]; then
            echo "::error::workflow file missing at $WF"
            exit 1
          fi
          cp "$WF" "${WF}.bak"

          yq eval --inplace ".on.workflow_dispatch.inputs.sync_path.default = \"${{ github.event.inputs.sync_path }}\"" "$WF"
          yq eval --inplace ".on.workflow_dispatch.inputs.operation_mode.default = \"${{ github.event.inputs.operation_mode }}\"" "$WF"
          yq eval --inplace ".on.workflow_dispatch.inputs.modify_date.default = \"${{ github.event.inputs.modify_date }}\"" "$WF"

          echo "Diff after reflection:"
          diff -u "${WF}.bak" "$WF" || true

      - name: Commit reflection (fallback)
        if: failure()
        env:
          WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          set -euo pipefail
          git config user.name "self-reflector[bot]"
          git config user.email "self-reflector@users.noreply.github.com"
          git add .github/workflows/enterprise-markdown-convert.yml

          # Prepare authenticated push URL using available token with fallback priority
          AUTH_TOKEN="${WORKFLOW_TOKEN:-${GITHUB_TOKEN-}}"
          ORIG_URL=$(git remote get-url origin)
          if [[ -n "${AUTH_TOKEN}" ]]; then
            AUTH_URL="https://x-access-token:${AUTH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            git remote set-url origin "$AUTH_URL"
          fi

          git commit --allow-empty -m "chore: reflect runtime inputs sync_path='${{ github.event.inputs.sync_path }}' operation_mode='${{ github.event.inputs.operation_mode }}' modify_date='${{ github.event.inputs.modify_date }}'"
          if ! git push; then
            echo "Warning: push failed. Inspect token scopes/permissions." >&2
          fi

      - name: Setup / Validate for build output
        run: echo "Reflection done, proceeding to build." 

  build:
    name: Format / Convert / PDF
    runs-on: ubuntu-latest
    needs: reflect-inputs
    steps:
      - name: Checkout repository (use updated commit)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Validate & normalize inputs
        id: validate
        run: |
          set -euo pipefail
          SYNC_PATH="$(echo '${{ github.event.inputs.sync_path }}' | tr -d '\r\n' | xargs)"
          if [[ -z "$SYNC_PATH" ]]; then
            echo "::error::sync_path input is empty"
            exit 1
          fi
          if [[ ! -d "$SYNC_PATH" ]]; then
            echo "::error::Directory does not exist: $SYNC_PATH"
            ls -1 | head -30
            exit 1
          fi
          MD_FILE=$(find "$SYNC_PATH" -maxdepth 1 -type f -name '*.md' | head -n1)
          if [[ -z "$MD_FILE" ]]; then
            echo "::error::No Markdown file found in $SYNC_PATH"
            exit 1
          fi
          echo "Using Markdown file: $MD_FILE"
          echo "SYNC_PATH=$SYNC_PATH" >> $GITHUB_ENV
          echo "MD_FILE=$MD_FILE" >> $GITHUB_ENV
          echo "OP_MODE=${{ github.event.inputs.operation_mode }}" >> $GITHUB_ENV
          echo "MODIFY_DATE=${{ github.event.inputs.modify_date }}" >> $GITHUB_ENV

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system-level dependencies
        run: |
          set -euo pipefail
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends pandoc bc wget ca-certificates
          sudo apt-get install -y --no-install-recommends xfonts-75dpi fonts-liberation fonts-dejavu

      - name: Install patched wkhtmltopdf (only if PDF mode)
        run: |
          set -euo pipefail
          if [[ "${{ env.OP_MODE }}" == *pdf* ]]; then
            sudo apt-get remove -y wkhtmltopdf || true
            TEMP_DEB=/tmp/wkhtmltox.deb
            wget -qO "$TEMP_DEB" https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
            sudo dpkg -i "$TEMP_DEB" || sudo apt-get install -f -y
            wkhtmltopdf --version
          else
            echo "Skipping wkhtmltopdf install (mode=${{ env.OP_MODE }})"
          fi

      - name: Setup and install Python virtualenv & deps
        run: |
          set -euo pipefail
          cd .github/src
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          if [[ -f requirements.txt ]]; then
            pip install -r requirements.txt
          else
            pip install beautifulsoup4 requests aiohttp aiofiles
          fi

      - name: Format Markdown with Prettier (if requested)
        run: |
          set -euo pipefail
          if [[ "${{ env.OP_MODE }}" == "format_and_convert" || "${{ env.OP_MODE }}" == "format_only" || "${{ env.OP_MODE }}" == "format_convert_pdf" ]]; then
            npx prettier --write "$MD_FILE"
          else
            echo "Skipping formatting (mode=${{ env.OP_MODE }})"
          fi

      - name: Convert Markdown to HTML (if requested)
        id: convert_html
        working-directory: .github/src
        run: |
          set -euo pipefail
          if [[ "${{ env.OP_MODE }}" == "format_and_convert" || "${{ env.OP_MODE }}" == "convert_only" || "${{ env.OP_MODE }}" == "format_convert_pdf" ]]; then
            source venv/bin/activate
            CONVERT_ARGS=()
            if [[ "${{ env.OP_MODE }}" == "format_and_convert" || "${{ env.OP_MODE }}" == "format_convert_pdf" ]]; then
              CONVERT_ARGS+=(--md-format)
            fi
            if [[ "${{ env.OP_MODE }}" == "format_and_convert" || "${{ env.OP_MODE }}" == "convert_only" || "${{ env.OP_MODE }}" == "format_convert_pdf" ]]; then
              CONVERT_ARGS+=(--md-to-html)
            fi
            python3 step_1_markdown_to_html_converter_V3_0.py "$MD_FILE" "$(pwd)/../../" "$(dirname "$MD_FILE")" "${CONVERT_ARGS[@]}"
          else
            echo "Skipping Markdown→HTML conversion (mode=${{ env.OP_MODE }})"
          fi

      - name: Convert HTML to PDF (if in PDF mode)
        id: generate_pdf
        working-directory: .github/src
        run: |
          set -euo pipefail
          if [[ "${{ env.OP_MODE }}" == "format_convert_pdf" ]]; then
            if [[ -z "${{ env.MODIFY_DATE }}" ]]; then
              echo "::error::modify_date is required for PDF generation"
              exit 1
            fi
            if ! date -d "${{ env.MODIFY_DATE }}" '+%Y-%m-%d' >/dev/null 2>&1; then
              echo "::error::modify_date is not a valid yyyy-mm-dd date: ${{ env.MODIFY_DATE }}"
              exit 1
            fi

            HTML_FILE=$(find "${{ env.SYNC_PATH }}" -maxdepth 3 -name '*.html' | head -n1)
            if [[ -z "$HTML_FILE" ]]; then
              echo "::error::No HTML file found to convert to PDF"
              exit 1
            fi

            source venv/bin/activate
            export MODIFY_DATE="${{ env.MODIFY_DATE }}"
            python3 step_2_convert_html_to_pdf.py "$HTML_FILE" "${{ env.MODIFY_DATE }}"
          else
            echo "Skipping PDF generation (mode=${{ env.OP_MODE }})"
          fi

      - name: Configure git for commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit & push changes if any
        run: |
          set -euo pipefail
          git add -A "${{ env.SYNC_PATH }}/" || true
          git add -A .github/src/styles/ || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            OP="${{ env.OP_MODE }}"
            COMMIT_MSG="enterprise: ${OP} for ${{ env.SYNC_PATH }} - generated on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
            git commit -m "$COMMIT_MSG"
            git push
          fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: conversion-results-${{ github.run_number }}-${{ github.job }}
          path: |
            ${{ env.SYNC_PATH }}/**/*.html
            ${{ env.SYNC_PATH }}/**/*.css
            ${{ env.SYNC_PATH }}/**/*.pdf
            .github/src/markdown_conversion.log
            conversion.log

      - name: Summary notices
        if: always()
        run: |
          {
            echo "## ✅ Conversion summary"
            echo "| Field | Value |"
            echo "|-------|-------|"
            echo "| Sync Path | \`${{ env.SYNC_PATH }}\` |"
            echo "| Mode | \`${{ env.OP_MODE }}\` |"
            if [[ "${{ env.OP_MODE }}" == "format_convert_pdf" ]]; then
              echo "| Modify Date | \`${{ env.MODIFY_DATE }}\` |"
            fi
            echo "| HTML Generated | ${{ steps.convert_html.outcome }} |"
            if [[ "${{ env.OP_MODE }}" == "format_convert_pdf" ]]; then
              echo "| PDF Generated | \`${{ env.generate_pdf.outcome }}\` |"
            fi
          } >> $GITHUB_STEP_SUMMARY
