# .github/workflows/generate_toc.yml
name: Generate TOC for PSD01 doc

on:
workflow_dispatch:

permissions:
contents: write

jobs:
generate_toc:
  runs-on: ubuntu-latest
  steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true

    - name: Debug: list repo tree
      run: |
        echo "=== Repo root ==="
        ls -R . || true

    - name: Find target Markdown
      id: findfile
      run: |
        FILE=$(find ndr/v6.0/psd01 -maxdepth 1 -type f -name 'ndr-v6.0-psd01.md' | head -n1)
        if [ -z "$FILE" ]; then
          echo "::error::Could not locate ndr/v6.0/psd01/ndr-v6.0-psd01.md"
          exit 1
        fi
        echo "path=$FILE" >> $GITHUB_OUTPUT

    - name: Install markdown-toc
      run: npm install --global markdown-toc

    - name: Generate TOC
      run: markdown-toc -i "${{ steps.findfile.outputs.path }}"

    - name: Commit & push if changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "${{ steps.findfile.outputs.path }}"
        if ! git diff --cached --quiet; then
          git commit -m "chore: update TOC in ${{ steps.findfile.outputs.path }}"
          git push
        else
          echo "No changes to commit."
        fi
