# .github/workflows/generate_toc.yml
name: 1.0 - Generate TOC for Markdown

on:
  workflow_dispatch:
    inputs:
      sync_path:
        description: |
          Path to the directory containing the Markdown file to update.
          Example: ndr/v6.0/psd01
        default: ndr/v6.0/psd01
        required: true

permissions:
  contents: write
  actions: write

jobs:
  generate_toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate inputs
        run: |
          set -e
          SYNC_PATH="${{ github.event.inputs.sync_path }}"
          echo "SYNC_PATH=${SYNC_PATH}"
          if [ ! -d "$SYNC_PATH" ]; then
            echo "::error::Directory not found: ${SYNC_PATH}"
            exit 1
          fi
          echo "SYNC_PATH=${SYNC_PATH}" >> $GITHUB_ENV

      - name: Install markdown-toc
        run: npm install --global markdown-toc

      - name: Find Markdown file
        id: findfile
        run: |
          MD_FILE=$(find "$SYNC_PATH" -maxdepth 1 -type f -name '*.md' | head -n1)
          if [ -z "$MD_FILE" ]; then
            echo "::error::No Markdown file found in ${SYNC_PATH}"
            exit 1
          fi
          echo "MD_FILE=${MD_FILE}" >> $GITHUB_ENV

      - name: Generate TOC
        run: |
          markdown-toc -i "${{ env.MD_FILE }}"

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add "${{ env.MD_FILE }}"
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update TOC in ${{ env.MD_FILE }}"
            git push
          fi
