# .github/workflows/toc.yml
name: Update TOC (manual)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  toc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: List files in target directory
        run: |
          echo "=== Listing ndr/v6.0/psd01/ ==="
          ls -R ndr/v6.0/psd01 || echo "Directory not found or empty"

      - name: Install markdown-toc
        run: npm install --global markdown-toc

      - name: Generate TOC for the PSD01 doc
        run: markdown-toc -i ndr/v6.0/psd01/ndr-v6.0-psd01.md

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ndr/v6.0/psd01/ndr-v6.0-psd01.md
          git commit -m "chore: update TOC in ndr-v6.0-psd01.md" || echo "No TOC changes"
          git push
