name: Update TOC (manual)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  toc:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Debug: Show working dir + repo tree
        run: |
          echo "PWD = $(pwd)"
          echo "=== Top-level files ==="
          ls -1
          echo "=== Recursive tree (depth=3) ==="
          find . -maxdepth 3 | sed 's|^\./||'

      - name: Locate target MD file
        id: findfile
        run: |
          FILE=$(find ndr -type f -name 'ndr-v6.0-psd01.md' | head -n1 || true)
          if [ -z "$FILE" ]; then
            echo "::error file=workflow::Could not find ndr-v6.0-psd01.md under ndr/"
            exit 1
          fi
          echo "Found: $FILE"
          echo "::set-output name=path::$FILE"

      - name: Install markdown-toc
        run: npm install --global markdown-toc

      - name: Generate TOC
        run: |
          markdown-toc -i "${{ steps.findfile.outputs.path }}"

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${{ steps.findfile.outputs.path }}"
          git diff --staged --quiet || (git commit -m "chore: update TOC in ${{ steps.findfile.outputs.path }}" && git push)
