name: 1.0 - Convert Markdown → HTML

on:
  workflow_dispatch:
    inputs:
      sync_path:
        description: |
          Path to the directory with the markdown file to convert to HTML.
          Example: ndr/v6.0/psd01
          Ensure the path is copied from GitHub and formatted correctly.
        default: ndr/v6.0/psd01
        required: true

jobs:
  convert-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Validate inputs
      - name: Validate inputs
        run: |
          set -e
          SYNC_PATH="${{ github.event.inputs.sync_path }}"
          echo "Received SYNC_PATH: $SYNC_PATH"
          if [ ! -d "$SYNC_PATH" ]; then
            echo "Invalid SYNC_PATH. Directory does not exist: $SYNC_PATH"
            exit 1
          fi
          echo "SYNC_PATH=$SYNC_PATH" >> $GITHUB_ENV

      # Step 3: Set up Node.js & Prettier
      - name: Set up Node.js & Install Prettier
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Prettier
        run: npm install -g prettier

      # Step 4: Set up Python & dependencies
      - name: Set up Python and install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Create venv & install Python deps + pandoc
        run: |
          cd .github/src
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install beautifulsoup4 requests
          sudo apt-get update
          sudo apt-get install -y pandoc
        shell: bash

      # Step 5: Format MD and Convert to HTML
      - name: Format MD and Convert to HTML
        env:
          SYNC_PATH: ${{ env.SYNC_PATH }}
          GIT_REPO_BASEDIR: ${{ github.workspace }}
        run: |
          echo "Sanitizing SYNC_PATH: $SYNC_PATH"
          SYNC_PATH=$(echo "$SYNC_PATH" | tr -d '\n' | xargs)

          MD_FILE=$(find "$SYNC_PATH" -name '*.md' | head -n 1)
          if [ -z "$MD_FILE" ]; then
            echo "No Markdown file found in $SYNC_PATH"
            exit 1
          fi

          OUTPUT_FILE="${MD_FILE%.md}.html"
          echo "Converting: $MD_FILE → $OUTPUT_FILE"

          # use the venv python
          .github/src/venv/bin/python3 .github/src/step_1_markdown_to_html_converter_V3_0.py \
            "$MD_FILE" \
            "$OUTPUT_FILE" \
            --git_repo_basedir "$GIT_REPO_BASEDIR"
        shell: bash

      # Step 6: Commit changes
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SYNC_PATH: ${{ env.SYNC_PATH }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          echo "Adding all changes within SYNC_PATH: $SYNC_PATH"
          git add -A "$SYNC_PATH/"

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          COMMIT_MESSAGE="Formatted and converted Markdown to HTML, updated modification dates"
          git commit -m "$COMMIT_MESSAGE"
          git push
        shell: bash
